config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about', to:'homes#about'
  
  resources :users
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :topics
  
  get '/favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, length: { maximum: 140 }
  validates :image, presence: true
  
  belongs_to :user
  has_many :favorites
  mount_uploader :image, ImageUploader
  has_many :favorite_users, through: :favorites, source: 'user'

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,uniqueness: true, length: {in: 2..15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
   
   add_flash_types :success, :info, :warning, :danger
   
   helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
   
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def index
    @favorite_topics = current_user.favorite_topics
  end
  
  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    
    if favorite.save
      redirect_to topics_path, success:'はーと'
    else
      redirect_to topics_path, danger: 'しっぱい'
    end
  end
  
  def destroy
    @favorite = Favorite.find_by(topic_id: params[:topic_id], user_id: current_user.id)
    @favorite.destroy
    redirect_to topics_path, success:"はーとさくじょ"
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to root_path, success: 'だん'
    else
      flash.now[:alart] = 'しっぱい'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'だん'
  end
  
  private
  
  def email_params
    params.require(:session).permit(:email)
  end
  
  def password_params
    params.require(:session).permit(:password)
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    @topics = Topic.all.includes(:favorite_users)
  end
  
  def new
    @topic = Topic.new
    @favorite = Favorite.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    
    if @topic.save
      redirect_to topics_path, success: "だん"
    else
      flash.now[:danger] = "しっぱい"
      render :new
    end
  end
  
  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to root_path, success: 'だん'
    else
      flash.now[:alart] = 'しっぱい'
      render :new
    end
  end
  
  private
  def params_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/homes/about.html.erb
<h1>つかいかた</h1>

app/views/homes/top.html.erb
 <% if !logged_in? %>
  <div class="top-btn">
  <%= link_to "さいんあっぷ", new_user_path, class:'btn-vertical-border'%>
  <%= link_to "ろぐいん", login_path, class:'btn-vertical-border'%>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <div class="header-menu">
      <%= link_to root_path do %>
          <h1><%= link_to "でもあぷり", root_path, class:'btn-vertical-border'%></h1>
      <% end %>
      <ul>
        <% if logged_in? %>
        <li><%= link_to "みんなのとうこう", topics_path, class:'btn-vertical-border'%></li>
        <li><%= link_to "おきにいり", favorites_index_path, class:'btn-vertical-border'%></li>
        <li><%= link_to "あっぷろーど", new_topic_path, class:'btn-vertical-border'%></li>
        <li><%= link_to "ろぐあうと", logout_path, method: :delete, class:'btn-vertical-border'%></li>
        <% else %>
        <li><%= link_to "さいんあっぷ", new_user_path, class:'btn-vertical-border'%></li>
        <li><%= link_to "ろぐいん", login_path, class:'btn-vertical-border'%></li>
        <li><%= link_to "つかいかた", homes_about_path, class:'btn-vertical-border'%></li>
        <% end %>
      </ul>
    </div>
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <i class="far fa-heart like-btn fa-2x"></i>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <i class="fas fa-heart like-btn fa-2x"></i>
              <% end %>
            <% end %>
            <%= topic.favorite_users.count %>
            <%= image_tag 'comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<%= form_for @topic do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.submit 'とうこう' %>
<% end %>

app/views/users/new.html.erb
<h2>さいんあっぷ</h2>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.text_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %><br>
  <%= f.submit "とうろく" %>
<% end %>